name: Go Docker Image

on:
  push:
    branches:
      - cks-upstream

permissions:
  contents: write
  packages: write

jobs:
  build-docker:
    name: Build + Release Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Images
        run: docker buildx build --platform linux/arm64,linux/amd64 --tag ghcr.io/chrisigel/zfs-exporter:latest --push .
